spring:
  ai:
    dashscope:
      chat:
        options:
          model: qwen3-max
      api-key: sk-ws-H.EYMDPRL.XhIH.MEQCIDYUCccAnq5u6Df7hi23dNdb5J5UdJXQP3ixkfNWnPO8AiBq0tfSSlf_YRYDojBuczcFb9djr4X8jn3XSZls1EK0Ag
    chat:
        memory:
          repository:
            jdbc:
              initialize-schema: always # 开启自动初始化表结构
              platform: mysql # 选择使用mysql的类型
      # schema: 如果想要使用自定义的表结构，可以在这里将自己的sql文件路径配置上去        
  data:
    redis:
      port: 6379 # reids的端口
      host: localhost # redis的地址
      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # jdbc驱动
    url: jdbc:mysql://localhost:3306/testdb2?characterEncoding=utf-8
    username: root # 账号
    password: 123456 # 密码
